events {
    worker_connections 1024;
}

http {
    # Application A upstream
    upstream app-a {
        least_conn;
        server 128.199.177.71:9000;
        server 128.199.177.71:9001;
    }

    # Application B upstream
    upstream app-b {
        least_conn;
        server 128.199.177.71:9002;
        server 128.199.177.71:9003;
    }

    # Error Handler

    # Server block for Application A
    server {
        listen 80;
        servername app1.orionzero.my.id;

        location / {
            proxy_pass 
        }
    }

    # server block for Application B
    server {
        listen 80;
        servername app1.orionzero.my.id;

        location / {
            
        }
    }
}